matrix:
  include:
    - language: node_js
      cache:
        directories:
        - "node_modules"
      before_script: ['cd src/AwesomeCMSCore/AwesomeCMSCore']
      script: ['npm install', 'npm run lint:js', 'npm run lint:style']
    - language: csharp
      mono: none
      dotnet: 2.0.0
      script:
        - dotnet restore src/AwesomeCMSCore
        - dotnet build src/AwesomeCMSCore

notifications:
  email:
    - ngohungphuc95@gmail.com