version: '3'

services:
  awesomecmscore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  module1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  webapplication1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


